### ISSUE TITLE
Criteo数据划分

### ISSUE THREAD

**Issue by zhujiem** [salmon1802/DCNv3#3]
请问Criteo上的效果是在Criteo_x1或Criteo_x4的划分上跑的吗？还是自己划分的数据。81.62的效果很好啊！

**Comment by salmon1802** [comment]
是按照Criteo_x4中的Criteo_x4_001进行设置的 :)  具体的运行日志可以在[这里](https://github.com/salmon1802/DCNv3/tree/master/checkpoints/Criteo_x4_10_h5)被找到。TDCNv3是SDCNv3之前的名字。

**Comment by zhujiem** [comment]
那这个提升是很大的，我学习一下！

**Comment by salmon1802** [comment]
不敢不敢，我纯小卡拉米，请问可以加您个微信吗，我的微信号是salmon1802
