### ISSUE TITLE
Cannot import name 'delete_model_files' from 'fuxictr.utils'

### ISSUE THREAD

**Issue by incredible-smurf** [salmon1802/DCNv3#5]
Sry, I can't run run_expid.py in your project. Did you make modifcations on fuxictr library? From fuxictr version v1 to v2 at https://github.com/reczoo/FuxiCTR/tree/v2.0.1, I can't find delete_model_files function.

**Comment by salmon1802** [comment]
This is one of my customized function, if you want to use FuxiCTR v2.0.1 to run DCNv3, you can remove the last line of run_expid.py: `delete_model_files(model_dir, params["model_id"])` and it will work fine.

The function is as follows:
```
def delete_model_files(model_dir, model_name):
    model_file = os.path.join(model_dir, model_name + '.model')
    os.remove(model_file)
```

**Comment by incredible-smurf** [comment]
Thx for your feedback. What about dataloader "H5DataLoader "? Could you give the code of it?

**Comment by salmon1802** [comment]
H5DataLoader is a library in FuxiCTR v2.0.1, which converts raw csv file to h5 file for data reading. You can find the usage of H5DataLoader in the source code of FuxiCTR v2.0.1.
