### ISSUE TITLE
The role of chunk

### ISSUE THREAD

**Issue by isCopyman** [salmon1802/DCNv3#6]
![image](https://github.com/user-attachments/assets/6314d0b8-c192-4e99-81d8-0e4a991622c6)
The role of chunks mentioned in section 3.1 is not reflected at all in the later part of the paper

**Comment by salmon1802** [comment]
Yes, we identified this issue. Please download the latest revised version. The previous version overlooked some details. The paper is now updated to the fifth version: [here](https://arxiv.org/abs/2407.13349).
