### ISSUE TITLE
FuxiCTR版本问题导致add_loss未执行。

### ISSUE THREAD

**Issue by zhujiem** [salmon1802/DCNv3#7]
最近定位到一个bug，导致重写的add_loss()未执行，受影响的版本包括FuxiCTRv2.0.2~2.3.3。部分模型FinalNe、DCNv3等可能没跑对。
https://github.com/reczoo/FuxiCTR/issues/122

**Comment by salmon1802** [comment]
好的，朱老师，我将在readme里强调这一点
